apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/liyocee/argocd_helloworld.git
    targetRevision: HEAD
    path: dev
  destinations:
    server: https://kubernetes.default.svc
    namespace: argocd-apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true