apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloword-app
spec:
  selector:
    matchLabels:
      app: helloworld-app
  template:
    metadata:
      labels:
        app: hellowrld-app
    spec:
      containers:
      - name: helloworld-app
        image: nanajanashia/argocd-app:1.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
