apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloword-app
spec:
  selector:
    matchLabels:
      app: helloworld-app
  replicas: 2
  template:
    metadata:
      labels:
        app: helloword-app
    spec:
      containers:
      - name: helloword-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
